CREATE DATABASE EXAM;
USE EXAM;
CREATE TABLE CLIENT_DHANANJAY
(
CLIENT_NAME VARCHAR(20),
CITY VARCHAR(20),
STATE VARCHAR(20),
BALANCE_DUE INTEGER(12)
);

INSERT INTO CLIENT_DHANANJAY VALUES("DHANAJAY","DELHI","DELHI",10000);
INSERT INTO CLIENT_DHANANJAY VALUES("DHANAJAY","PUNE","MAHARASHTRA",15000);
INSERT INTO CLIENT_DHANANJAY VALUES("HARSHAL","PUNE","MAHARASHTRA",15000);
INSERT INTO CLIENT_DHANANJAY VALUES("RUSHI","MUMBAI","MAHARASHTRA",5000);
INSERT INTO CLIENT_DHANANJAY VALUES("PREM","BHANDARA","MAHARASHTRA",1000);
INSERT INTO CLIENT_DHANANJAY VALUES("AMOL","RANCHI","JHARKHAND",2000);

SELECT * FROM CLIENT_DHANANJAY;
DESC CLIENT_DHANANJAY;
SELECT DISTINCT CLIENT_NAME FROM CLIENT_DHANANJAY;

SELECT CLIENT_NAME FROM CLIENT_DHANANJAY ORDER BY CLIENT_NAME ASC;
SELECT CLIENT_NAME,CITY,STATE FROM CLIENT_DHANANJAY;
SELECT * FROM CLIENT_DHANANJAY WHERE CITY="DELHI";
ALTER TABLE CLIENT_DHANANJAY  ADD MOBILE_PHONE int(12); 
SELECT  CLIENT_NAME FROM CLIENT_DHANANJAY WHERE CITY LIKE 'B%';
SELECT  CLIENT_NAME FROM CLIENT_DHANANJAY  WHERE (CITY = 'DELHI') OR (CITY = 'MUMBAI' AND CITY != 'RANCHI');
SELECT * FROM CLIENT_DHANANJAY WHERE BALANCE_DUE<10000;
/*******************************************************************************************************************************************/
CREATE TABLE PRODUCT_DHANANJAY
(
PRODUCT_NAME VARCHAR(20),
COST_PRICE INT,
QUANTITY INT,
PROFIT INT
);
INSERT INTO PRODUCT_DHANANJAY VALUES("SHOE",6000,20,2000);
INSERT INTO PRODUCT_DHANANJAY VALUES("T-SHIRT",2000,40,1500);
INSERT INTO PRODUCT_DHANANJAY VALUES("SHADES",1000,15,800);
INSERT INTO PRODUCT_DHANANJAY VALUES("JEANS",4000,10,3000);
INSERT INTO PRODUCT_DHANANJAY VALUES("WATCH",3000,30,1000);
SELECT * FROM PRODUCT_DHANANJAY;
SELECT PRODUCT_NAME FROM PRODUCT_DHANANJAY;
UPDATE PRODUCT_DHANANJAY SET COST_PRICE = 5000 WHERE PRODUCT_NAME="SHOE";
 DELETE FROM PRODUCT_DHANANJAY  WHERE QUANTITY>=20;
 SELECT PRODUCT_NAME FROM PRODUCT_DHANANJAY WHERE (((cost_price)<3000) );
/********************************************************************************************************************************************/
CREATE TABLE SALESMAN_DHANANJAY
(
S_NAME VARCHAR(20),
SALARY INT,
CITY VARCHAR(10),
ANNUAL_SALARY INT DEFAULT ( SALARY*12)
);
INSERT INTO SALESMAN_DHANANJAY(S_NAME ,SALARY ,CITY ) VALUES ("SUDHANSH",35000,"PUNE" );
INSERT INTO SALESMAN_DHANANJAY(S_NAME ,SALARY ,CITY ) VALUES ("NAYAN",2000,"AMRAVATI" );
INSERT INTO SALESMAN_DHANANJAY(S_NAME ,SALARY ,CITY ) VALUES ("HARSHAL",3000,"JALGAO" );
INSERT INTO SALESMAN_DHANANJAY(S_NAME ,SALARY ,CITY ) VALUES ("ROHIT",3500,"AHMEDNAGAR" );
INSERT INTO SALESMAN_DHANANJAY(S_NAME ,SALARY ,CITY ) VALUES ("KUNAL",3100,"MORSHI" );

SELECT * FROM SALESMAN_DHANANJAY;
SELECT S_NAME FROM SALESMAN_DHANANJAY WHERE SALARY=3000;
UPDATE SALESMAN_DHANANJAY SET CITY = "PUNE" WHERE S_NAME ="KUNAL";
DELETE FROM SALESMAN_DHANANJAY WHERE salary>=3000;
ALTER TABLE SALESMAN_DHANANJAY RENAME TO DHA_SALESMAN;
SELECT * FROM DHA_SALESMAN;
SELECT ANNUAL_SALARY FROM DHA_SALESMAN;
/****************************************************************************************************************/
CREATE TABLE BILL 
(BILL_DATE DATE,
AMOUNT INT);
INSERT INTO BILL VALUES('2002-01-24',50000),('2001-02-18',10000);
SELECT * FROM BILL;
select * from BILL WHERE BILL_DATE = '2002-01-24';

/******************************************************************************************************************/
 create table Employee_DHANANJAY (
Emp_no int,
branch_no varchar(5),
name varchar(25),
dept varchar(15),
manager int,
sallary int,AGE INT
);
DELIMITER //
CREATE  TRIGGER age_check
      BEFORE INSERT 
     ON EMPLOYEE_DHANANJAY
      FOR EACH ROW
      begin

     IF NEW.AGE <18 THEN
     signal sqlstate'45000'
     SET message_text='AGE MUST BE 18';
END IF;
END;//
DELIMITER ;
insert into Employee_DHANANJAY values (101,'2005','A','science',103,10000,20);
insert into Employee_DHANANJAY values (102,'2005','B','science',103,20000,30);
insert into Employee_DHANANJAY values (103,'2005','C','science',null,30000,15);
 select* FROM Employee_DHANANJAY;
select COUNT(distinct MANAGER) FROM employee;
select dept,avg(sallary) from Employee group by dept having avg(sallary)>20000;
select dept,count(emp_no) from Employee group by dept having count(emp_no)>2;
select dept,count(emp_no) from Employee group by dept;
CREATE VIEW EMP AS select NAME,EMP_NO FROM employee;
select * FROM EMP;
DELIMITER //
CREATE procedure DISPLAY_HR()
BEGIN
select* FROM employee WHERE DEPT='HR';
END
//
DELIMITER ;
CALL DISPLAY_HR();